### PR TITLE
enable build bcachefs-tools without rust

### PR DESCRIPTION
**Pull request by benstonezhang**
Add a dedicated Makefile.pc for special build without rust toolchain.
cmd_mount is new added, cmd_subvolume is add back from previous code base.

### CODE REVIEW

**Comment by koverstreet** [comment]
No, we're going to be increasing our use of Rust in the future, not decreasing it.

**Comment by benstonezhang** [comment]
but how the environment without a rust toolchain? for embedded device, most of them does not have a rust toolchain available for now. why we abandon them?

**Comment by koverstreet** [comment]
Well, they're going to have to get with the times. C is 50 years old and we finally have something better; I can't hold back the whole project for people who don't want to update their toolchains.

**Comment by benstonezhang** [comment]
OK. I will try to maintain a pure C copy of this tool, and keep track your progress.
BTW, I think rust is the successor of C++, not C. There is still some place for C.

**Pull request closed without merging**
