### PR TITLE
extend dependency to real for ubuntu 20.04

### PR DESCRIPTION
**Pull request by iav**

### CODE REVIEW

**Comment by marcin-github** [comment]
Hi,
which package in Ubuntu contains rst2man which is needed since a couple of weeks?

**Comment by iav** [comment]
> which package in Ubuntu contains rst2man

`python3-docutils`

**Comment by marcin-github** [comment]
Thanks:) I was looking for rst2man in Gentoo but in this distro this is `rst2man.py` . So I couldn't find.

**Review by koverstreet — COMMENTED** [review]
Can you update debian/control too? Bonus points for testing it

**Comment by iav** [comment]
Not sure how to test `control`: if no such packages on build system — make (without deb) fails; if packages are present — all dependencies already met, nothing to fail.
But I run `make deb` with suggested changes, and it finished successful.

**Comment by koverstreet** [comment]
Please squash your commits, and give it a better description - "add missing python3-docutils dependency", perhaps

**Comment by rkarlsba** [comment]
apt install docutils

worked for me on debian bullseye

**Pull request merged**
