### PR TITLE
feature: allow cmd mount to accept only 1 block device, then mount by UUID

### PR DESCRIPTION
**Pull request by truongsinh**
This allows bcachefs to be mounted by /etc/fstab

Ref https://www.reddit.com/r/bcachefs/comments/o19vw9/how_to_mount_on_boot/

### CODE REVIEW

**Comment by truongsinh** [comment]
FYI, this should be merged after https://github.com/koverstreet/bcachefs-tools/pull/141

**Comment by phedders** [comment]
Would love to see this functionality merged... for 6.7 mainline would be awesome...

**Comment by chayleaf** [comment]
it looks like you forgot to apply rustfmt?

**Comment by JohnRTitor** [comment]
Any updates here? I am on NixOS with Kernel 6.8, looks like if I enable systemd initrd, it fails to mount bcachefs.
Can this PR solve it? @koverstreet would love your input.

**Comment by koverstreet** [comment]
I'll get to this when I can; working on some urgent debugging and repair code right now

**Comment by JohnRTitor** [comment]
@truongsinh can you rebase this?

**Comment by koverstreet** [comment]
We have this functionality now

**Pull request closed without merging**
